initial_data_analysis:
  description: >
    Read the CSV file located at {file_path} and perform initial data analysis.
    Use the CSVAnalysisTool to get the head of the DataFrame, data types, and
    basic statistics.
    Execute simple code snippets interacting with the CSV data, one snippet at
    a time.
    Ensure you use the exact file path {file_path} without modifying it.
    Look for interesting insights in the data.
  expected_output: >
    A comprehensive report with the of the DataFrame, data types, and basic
    statistics.

advanced_data_analysis:
  description: >
    Perform advanced data analysis on the CSV file located at {file_path}.
    Include statistical summaries, correlations, and insights.
    Execute simple code snippets interacting with the CSV data, one snippet at
    a time.
    Don't plot charts.
    Filter out non numeric columns on the needed operations.
    Ensure you use the exact file path {file_path} without modifying it.
  expected_output: >
    A comprehensive report with statistical summaries, correlations, and key
    insights

generate_charts:
  description: >
    Generate charts based on the CSV data analysis, file located at {file_path}.
    Execute simple code snippets for each chart, one at a time.
    Save each chart with a unique name and provide URLs for all generated images.
    Ensure you use the exact file path {file_path} without modifying it.
  expected_output: >
    A list of unique URLs for all generated chart images.

generate_report_plan:
  description: >
    Develop a detailed plan for compiling a markdown report on the big car
    manufacturer using the outputs of the initial data analysis, advanced data
    analysis, and generated charts.


    The plan must be a list sections with:


    title, full_description, charts, insights, analysis


    Ensure the plan pieces together the content
    step-by-step, verifying each part before moving on.
  expected_output: >
    A comprehensive plan for the markdown report, outlining sections, content,
    and structure.

write_markdown_report:
  description: >
    Write a markdown report on the big car manufacturer using the plan developed
    in the previous task.
    Ensure the report is well-structured, coherent, and includes all required
    sections.
    Use the provided plan to guide the report writing process.
    Don't forget to include the generated charts and visualizations in the
    report, but only if there is any, don't come up with new images.
  expected_output: >
    A complete markdown report on the big car manufacturer, following the
    structure and content outlined in the plan without the "```" code blocks.