initial_data_analysis:
  description: >
    Read the CSV file located at {file_path} and perform initial data analysis.
    Use the CSVAnalysisTool to get the head of the DataFrame, data types, and
    basic statistics.
    Execute simple code snippets interacting with the CSV data, one snippet at
    a time.
    Ensure you use the exact file path {file_path} without modifying it.
    Look for interesting insights in the data.
  expected_output: >
    A comprehensive report with the of the DataFrame, data types, and basic
    statistics.

advanced_data_analysis:
  description: >
    Perform advanced data analysis on the CSV file located at {file_path}.
    Include statistical summaries, correlations, and insights.
    Execute simple code snippets interacting with the CSV data, one snippet at
    a time.
    Don't plot charts.
    Filter out non numeric columns on the needed operations.
    Ensure you use the exact file path {file_path} without modifying it.
  expected_output: >
    A comprehensive report with statistical summaries, correlations, and key
    insights

generate_charts:
  description: >
    Generate charts based on the CSV data analysis, file located at {file_path}.
    Execute simple code snippets for each chart, one at a time.
    Save each chart with a unique name and provide URLs for all generated images.
    Ensure you use the exact file path {file_path} without modifying it.
  expected_output: >
    A list of unique URLs for all generated chart images.

research_company:
  description: >
    Conduct in-depth research on Tesla and the provided data
    to develop a comprehensive plan for the markdown report.
    Use the plan developed in the previous task to guide your research.
    Look for additional insights and information that could be included in the
    report.
  expected_output: >
    A detailed research report on Tesla, including additional
    insights and information, and the original source where the information
    was found with the website link.

plan_report:
  description: >
    Plan a report about all the findings from the analysis you are provided with
    about Tesla.
    Use all the information and data you are being provided with to create a
    comprehensive and well-organized report plan.
  expected_output: >
    A comprehensive report plan, outlining sections, content, and structure.
    Plan individual sections, each with a descriptive title, all data necessary
    to be in there, chart images paths that should be included, and a long thoughtful
    draft of the section and why it matters.

write_markdown_report:
  description: >
    Write a markdown report section on Tesla using the plan bellow.
    Ensure the report is well-structured, coherent, and includes all relevant data.
    Use the provided plan to guide the report writing process.
    Don't forget to include the generated charts and visualizations in the
    report, but only if there is any, don't come up with new images.
    You must only use the images provided in the plan, if there are any. NEVER use non-reference images.


    Syntax for adding images to the markdown report: ![alt text](Isolated.png "Title")

    When you have all the necessary information to write just give your final answer.


    Plan:
    {plan}
  expected_output: >
    A complete markdown report on tesla, following the
    structure and content outlined in the plan without the "```" code blocks.